# Abaikan kodingan ini

In [11]:
import pandas as pd
df=pd.read_csv("datasama.csv")
df['Products Listing']=df['Products Listing'].replace(to_replace=r'\r\r\n', value='', regex=True)
df['Manufaktur']=df['Manufaktur'].replace(to_replace=r'\r\r\n', value='', regex=True)
df.replace('^\s+', '', regex=True, inplace=True)
df.replace('\s+$', '', regex=True, inplace=True)
# df=pd.Series()
# df=df.str.title()
df['Products Listing']=df['Products Listing'].str.title()
df['Manufaktur']=df['Manufaktur'].str.title()
df.to_csv("datasamafix.csv")

# kodingan yang dijalankan

In [1]:
import MySQLdb
import mysql.connector
import pandas as pd
import datetime 

now = datetime.datetime.now()

db = MySQLdb.connect(host="localhost",    # your host, usually localhost
                     user="halal1",         # your username
                     passwd="123ewq",  # your password
                     db="halal")        # name of the data base
df=pd.read_csv("B:/Tugas akhir/Analisis Bab6/update Halal/3.dataprdanbrsamaFIX.csv",encoding='latin1')
# you must create a Cursor object. It will let
#  you execute all the queries you need
cur = db.cursor()
cur.execute("SELECT id from `foodproducts` WHERE `fname`='bkkjkjk'")
test = cur.fetchall()

for x in df.iterrows():
   
    cur.execute(("SELECT id from `foodproducts` WHERE `fname`='")+str(x[1][1])+"'")
#     print(("SELECT id from `foodproducts` WHERE `fname`='")+str(x[1][1])+"'")
    
    results = cur.fetchall()
    if results != test :
        print(("SELECT id from `foodproducts` WHERE `fname`='")+str(x[1][0])+"'")
        sql1=("INSERT INTO `foodproduct_manufacture`(`foodproduct_id`, `manufacture_id`, `created_at`, `updated_at`) VALUES (%s,%s,%s,%s)")
#         print(("INSERT INTO `foodproduct_manufacture`(`foodproduct_id`, `manufacture_id`, `created_at`, `updated_at`) VALUES (%s,%s,%s,%s)"))
        val1= (results[0],x[1][0],now,now)
#         print(results[0])
        cur.execute(sql1,val1)
        db.commit()
#         print("berhasil")
        cur.execute(("SELECT max(id) FROM certificates"))
        IDcer = cur.fetchall()[0][0]+1
        sql2=("INSERT INTO `certificates`(`id`, `cCode`, `cExpire`, `cStatus`, `cOrganization`, `created_at`, `updated_at`) VALUES (%s,%s,%s,%s,%s,%s,%s)")
        val2= (IDcer,str(x[1][3]),str(x[1][5]),"",str(x[1][4]),now,now)
        cur.execute(sql2,val2)
        db.commit()
#         print("berhasil1")
        sql3= "INSERT INTO `foodproduct_certificate`(`foodproduct_id`, `certificate_id`, `created_at`, `updated_at`) VALUES (%s,%s,%s,%s)"
        val3=(results[0],IDcer,now,now)
        cur.execute(sql3, val3)
        db.commit()
        
        #print(results)
  #     cur.execute("")
    #   db.commit()

SELECT id from `foodproducts` WHERE `fname`='1% Low Fat Milk'
SELECT id from `foodproducts` WHERE `fname`='100% Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Grape Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Grape Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Grape Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Grape Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Juice Tomato'
SELECT id from `foodproducts` WHERE `fname`='100% Juice White Grape'
SELECT id from `foodproducts` WHERE `fname`='100% Lemon Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Lemon Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Lemon Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Lemon Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Prune Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Prune Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Pure Honey'
SELECT id from `foodproducts` WHERE `fname`='100% Pure Maple Syrup'
SELECT id from `foodproducts` WHERE `fname`='100% Pure Maple Syrup'
SELECT id from `foodproducts` WHERE `fname`='100% Pure Orange Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Pure Orange Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Tomato Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Tomato Juice'
SELECT id from `foodproducts` WHERE `fname`='100% White Grape Juice'
SELECT id from `foodproducts` WHERE `fname`='100% White Grape Juice'
SELECT id from `foodproducts` WHERE `fname`='100% White Grape Juice'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='100% Whole Wheat Bread'
SELECT id from `foodproducts` WHERE `fname`='2% Reduced Fat Milk'
SELECT id from `foodproducts` WHERE `fname`='2% Reduced Fat Milk'
SELECT id from `foodproducts` WHERE `fname`='8 Hamburger Buns'
SELECT id from `foodproducts` WHERE `fname`='8 Hamburger Buns'
SELECT id from `foodproducts` WHERE `fname`='8 Hamburger Buns'
SELECT id from `foodproducts` WHERE `fname`='8 Hamburger Buns'
SELECT id from `foodproducts` WHERE `fname`='All Natural Sour Cream'
SELECT id from `foodproducts` WHERE `fname`='All Natural Sour Cream'
SELECT id from `foodproducts` WHERE `fname`='All Natural Sour Cream'
SELECT id from `foodproducts` WHERE `fname`='All Natural Sour Cream'
SELECT id from `foodproducts` WHERE `fname`='All Natural Sour Cream'
SELECT id from `foodproducts` WHERE `fname`='All Natural Sour Cream'
SELECT id from `foodproducts` WHERE `fname`='All Natural Sour Cream'
SELECT id from `foodproducts` WHERE `fname`='Almond Butter'
SELECT id from `foodproducts` WHERE `fname`='Almond Cookies'
SELECT id from `foodproducts` WHERE `fname`='Almond Cookies'
SELECT id from `foodproducts` WHERE `fname`='Almond Cookies'
SELECT id from `foodproducts` WHERE `fname`='Almond Milk'
SELECT id from `foodproducts` WHERE `fname`='Apple Cider Vinegar'
SELECT id from `foodproducts` WHERE `fname`='Apple Cider Vinegar'
SELECT id from `foodproducts` WHERE `fname`='Apple Cider Vinegar'
SELECT id from `foodproducts` WHERE `fname`='Apple Crumble'
SELECT id from `foodproducts` WHERE `fname`='Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='Apple Juice'
SELECT id from `foodproducts` WHERE `fname`='Apple Strudel'
SELECT id from `foodproducts` WHERE `fname`='Applesauce'
SELECT id from `foodproducts` WHERE `fname`='Applesauce'
SELECT id from `foodproducts` WHERE `fname`='Applesauce'
SELECT id from `foodproducts` WHERE `fname`='Applesauce'
SELECT id from `foodproducts` WHERE `fname`='Applesauce'
SELECT id from `foodproducts` WHERE `fname`='Applesauce'
SELECT id from `foodproducts` WHERE `fname`='Applesauce Cinnamon'
SELECT id from `foodproducts` WHERE `fname`='Applesauce Original'
SELECT id from `foodproducts` WHERE `fname`='Aspartame'
SELECT id from `foodproducts` WHERE `fname`='Aurora Sauce'
SELECT id from `foodproducts` WHERE `fname`='Ayam Bakar'
SELECT id from `foodproducts` WHERE `fname`='Ayam Bakar Madu'
SELECT id from `foodproducts` WHERE `fname`='Baking Powder'
SELECT id from `foodproducts` WHERE `fname`='Baking Powder'
SELECT id from `foodproducts` WHERE `fname`='Bakso Daging'
SELECT id from `foodproducts` WHERE `fname`='Barbecue Sauce'
SELECT id from `foodproducts` WHERE `fname`='Bbq Sauce'
SELECT id from `foodproducts` WHERE `fname`='Bbq Sauce'
SELECT id from `foodproducts` WHERE `fname`='Bbq Seasoning'
SELECT id from `foodproducts` WHERE `fname`='Beef Jerky'
SELECT id from `foodproducts` WHERE `fname`='Beef Patty'
SELECT id from `foodproducts` WHERE `fname`='Beef Rendang'
SELECT id from `foodproducts` WHERE `fname`='Big Mac'
SELECT id from `foodproducts` WHERE `fname`='Big Tasty'
SELECT id from `foodproducts` WHERE `fname`='Biscotti Almond'
SELECT id from `foodproducts` WHERE `fname`='Bite Size Tortilla Chips'
SELECT id from `foodproducts` WHERE `fname`='Black Bean Sauce'
SELECT id from `foodproducts` WHERE `fname`='Black Bean Sauce'
SELECT id from `foodproducts` WHERE `fname`='Black Pepper Ground'
SELECT id from `foodproducts` WHERE `fname`='Black Pepper Powder'
SELECT id from `foodproducts` WHERE `fname`='Black Pepper Sauce'
SELECT id from `foodproducts` WHERE `fname`='Black Pepper Sauce'
SELECT id from `foodproducts` WHERE `fname`='Blackcurrant'
SELECT id from `foodproducts` WHERE `fname`='Blueberry'
SELECT id from `foodproducts` WHERE `fname`='Blueberry Cake'
SELECT id from `foodproducts` WHERE `fname`='Blueberry Cheese Cake'
SELECT id from `foodproducts` WHERE `fname`='Bran Flakes'
SELECT id from `foodproducts` WHERE `fname`='Bread Butter Pudding'
SELECT id from `foodproducts` WHERE `fname`='Brilliant Blue'
SELECT id from `foodproducts` WHERE `fname`='Brownies'
SELECT id from `foodproducts` WHERE `fname`='Burger Bun'
SELECT id from `foodproducts` WHERE `fname`='Butter'
SELECT id from `foodproducts` WHERE `fname`='Butter'
SELECT id from `foodproducts` WHERE `fname`='Butter'
SELECT id from `foodproducts` WHERE `fname`='Butter Cake'
SELECT id from `foodproducts` WHERE `fname`='Butter Cake'
SELECT id from `foodproducts` WHERE `fname`='Butter Chicken'
SELECT id from `foodproducts` WHERE `fname`='Butter Salted'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Pancake Mix'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Pancakes'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Pancakes'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Pancakes'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Pancakes'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Pancakes'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Pancakes'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Pancakes'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'

SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Buttermilk Waffles'
SELECT id from `foodproducts` WHERE `fname`='Cake'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Canola Oil'
SELECT id from `foodproducts` WHERE `fname`='Cappuccino'
SELECT id from `foodproducts` WHERE `fname`='Caramel Mix'
SELECT id from `foodproducts` WHERE `fname`='Cardamom Powder'
SELECT id from `foodproducts` WHERE `fname`='Carmoisine'
SELECT id from `foodproducts` WHERE `fname`='Carrot Cake'
SELECT id from `foodproducts` WHERE `fname`='Carrot Cake'
SELECT id from `foodproducts` WHERE `fname`='Carrot Cake'
SELECT id from `foodproducts` WHERE `fname`='Carrot Cake'
SELECT id from `foodproducts` WHERE `fname`='Cheese Cake'
SELECT id from `foodproducts` WHERE `fname`='Cheese Cookies'
SELECT id from `foodproducts` WHERE `fname`='Cheese Crackers'
SELECT id from `foodproducts` WHERE `fname`='Cheese Dip'
SELECT id from `foodproducts` WHERE `fname`='Cheese Tart'
SELECT id from `foodproducts` WHERE `fname`='Cheese Tart'
SELECT id from `foodproducts` WHERE `fname`='Chicken Bolognaise'
SELECT id from `foodproducts` WHERE `fname`='Chicken Breast Strips'
SELECT id from `foodproducts` WHERE `fname`='Chicken Bun'
SELECT id from `foodproducts` WHERE `fname`='Chicken Marinated'
SELECT id from `foodproducts` WHERE `fname`='Chicken Pie'
SELECT id from `foodproducts` WHERE `fname`='Chicken Pie'
SELECT id from `foodproducts` WHERE `fname`='Chicken Puff'
SELECT id from `foodproducts` WHERE `fname`='Chicken Soup'
SELECT id from `foodproducts` WHERE `fname`='Chicken Soup'
SELECT id from `foodproducts` WHERE `fname`='Chicken Tikka Masala'
SELECT id from `foodproducts` WHERE `fname`='Chiffon'
SELECT id from `foodproducts` WHERE `fname`='Chiffon Cake'
SELECT id from `foodproducts` WHERE `fname`='Chili Flakes'
SELECT id from `foodproducts` WHERE `fname`='Chili Powder'
SELECT id from `foodproducts` WHERE `fname`='Chili Sauce'
SELECT id from `foodproducts` WHERE `fname`='Chili Sauce'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Brown Ht'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Bun'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Cheese Cake'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Chip Cookies'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Chip Cookies'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Chips Cookies'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Danish'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Flavored Syrup'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Flavored Syrup'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Flavored Syrup'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Flavored Syrup'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Paste'
SELECT id from `foodproducts` WHERE `fname`='Chocolate Paste'
SELECT id from `foodproducts` WHERE `fname`='Chopped Garlic'
SELECT id from `foodproducts` WHERE `fname`='Chunky Salsa'
SELECT id from `foodproducts` WHERE `fname`='Chunky Salsa Mild'
SELECT id from `foodproducts` WHERE `fname`='Cinnamon Applesauce'
SELECT id from `foodproducts` WHERE `fname`='Cinnamon Applesauce'
SELECT id from `foodproducts` WHERE `fname`='Cinnamon Applesauce'
SELECT id from `foodproducts` WHERE `fname`='Cinnamon Applesauce'
SELECT id from `foodproducts` WHERE `fname`='Cinnamon Applesauce'
SELECT id from `foodproducts` WHERE `fname`='Cinnamon Powder'
SELECT id from `foodproducts` WHERE `fname`='Cinnamon Raisin Bagels'
SELECT id from `foodproducts` WHERE `fname`='Cinnamon Roll'
SELECT id from `foodproducts` WHERE `fname`='Cinnamon Waffles'
SELECT id from `foodproducts` WHERE `fname`='Citric Acid'
SELECT id from `foodproducts` WHERE `fname`='Classic Yellow Mustard'
SELECT id from `foodproducts` WHERE `fname`='Classic Yellow Mustard'
SELECT id from `foodproducts` WHERE `fname`='Clove Powder'
SELECT id from `foodproducts` WHERE `fname`='Clover Honey'
SELECT id from `foodproducts` WHERE `fname`='Clover Honey'
SELECT id from `foodproducts` WHERE `fname`='Clover Honey'
SELECT id from `foodproducts` WHERE `fname`='Cocktail Sauce'
SELECT id from `foodproducts` WHERE `fname`='Coconut'
SELECT id from `foodproducts` WHERE `fname`='Coconut Cookies'
SELECT id from `foodproducts` WHERE `fname`='Coconut Cookies'
SELECT id from `foodproducts` WHERE `fname`='Coconut Cookies'
SELECT id from `foodproducts` WHERE `fname`='Coconut Cream Powder'
SELECT id from `foodproducts` WHERE `fname`='Coconut Oil'
SELECT id from `foodproducts` WHERE `fname`='Coconut Water'
SELECT id from `foodproducts` WHERE `fname`='Coffee Creamer'
SELECT id from `foodproducts` WHERE `fname`='Coffee Creamer'
SELECT id from `foodproducts` WHERE `fname`='Coffee Creamer'
SELECT id from `foodproducts` WHERE `fname`='Coffee Creamer'
SELECT id from `foodproducts` WHERE `fname`='Coffee Jelly'
SELECT id from `foodproducts` WHERE `fname`='Cola'
SELECT id from `foodproducts` WHERE `fname`='Cole Slaw'
SELECT id from `foodproducts` WHERE `fname`='Coriander Powder'
SELECT id from `foodproducts` WHERE `fname`='Corn Oil'
SELECT id from `foodproducts` WHERE `fname`='Corn Oil'
SELECT id from `foodproducts` WHERE `fname`='Corn Oil'
SELECT id from `foodproducts` WHERE `fname`='Corn Oil'
SELECT id from `foodproducts` WHERE `fname`='Corn Oil'
SELECT id from `foodproducts` WHERE `fname`='Corn Oil'
SELECT id from `foodproducts` WHERE `fname`='Corn Oil'
SELECT id from `foodproducts` WHERE `fname`='Corn Oil'
SELECT id from `foodproducts` WHERE `fname`='Corn Oil'
SELECT id from `foodproducts` WHERE `fname`='Corn Oil'
SELECT id from `foodproducts` WHERE `fname`='Cottage Cheese'
SELECT id from `foodproducts` WHERE `fname`='Cracked Peppercorn Sauce'
SELECT id from `foodproducts` WHERE `fname`='Cranberry Juice'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese Spread'
SELECT id from `foodproducts` WHERE `fname`='Cream Cheese Spread'
SELECT id from `foodproducts` WHERE `fname`='Cream Puff'
SELECT id from `foodproducts` WHERE `fname`='Cream Puff'
SELECT id from `foodproducts` WHERE `fname`='Cream Puff'
SELECT id from `foodproducts` WHERE `fname`='Cream Soda'
SELECT id from `foodproducts` WHERE `fname`='Creamy French Dressing'
SELECT id from `foodproducts` WHERE `fname`='Creamy French Dressing'
SELECT id from `foodproducts` WHERE `fname`='Creamy Peanut Butter'
SELECT id from `foodproducts` WHERE `fname`='Creamy Peanut Butter'
SELECT id from `foodproducts` WHERE `fname`='Creamy Peanut Butter'
SELECT id from `foodproducts` WHERE `fname`='Creamy Peanut Butter'
SELECT id from `foodproducts` WHERE `fname`='Creamy Peanut Butter'
SELECT id from `foodproducts` WHERE `fname`='Creamy Peanut Butter'
SELECT id from `foodproducts` WHERE `fname`='Creamy Peanut Butter'
SELECT id from `foodproducts` WHERE `fname`='Creamy Peanut Butter'
SELECT id from `foodproducts` WHERE `fname`='Creamy Peanut Butter'
SELECT id from `foodproducts` WHERE `fname`='Creamy Peanut Butter'

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-cb41e3755ca2>", line 21, in <module>
    cur.execute(("SELECT id from `foodproducts` WHERE `fname`='")+str(x[1][1])+"'")
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\MySQLdb\cursors.py", line 312, in _query
    db.query(q)
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\MySQLdb\connections.py", line 224, in query
    _mysql.connection.query(self, query)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2018, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1095, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 347, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Users\PidiePie\Anaconda3\lib\inspect.py", line 1500, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "C:\Users\PidiePie\Anaconda3\lib\inspect.py", line 1458, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "C:\Users\PidiePie\Anaconda3\lib\inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "C:\Users\PidiePie\Anaconda3\lib\inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\py\_vendored_packages\apipkg.py", line 195, in __getattribute__
    return getattr(getmod(), name)
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\py\_vendored_packages\apipkg.py", line 179, in getmod
    x = importobj(modpath, None)
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\py\_vendored_packages\apipkg.py", line 69, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pytest.py", line 8, in <module>
    from _pytest.config import cmdline
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 17, in <module>
    from pkg_resources import parse_version
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3126, in <module>
    @_call_aside
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 572, in _build_master
    ws = cls()
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 565, in __init__
    self.add_entry(entry)
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 621, in add_entry
    for dist in find_distributions(entry, True):
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1968, in find_on_path
    for dist in factory(fullpath):
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2038, in distributions_from_metadata
    root, entry, metadata, precedence=DEVELOP_DIST,
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2495, in from_location
    py_version=py_version, platform=platform, **kw
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2870, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2459, in _version_from_file
    line = next(iter(version_lines), '')
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2649, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1414, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1410, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "C:\Users\PidiePie\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1522, in _get
    with open(path, 'rb') as stream:
KeyboardInterrupt

KeyboardInterrupt:

# abaikan

In [1]:
import pandas as pd
df=pd.read_csv("datasama.csv",encoding='utf-8',index_col=None)
df=df['Products Listing'].capitalize()
df

AttributeError: 'Series' object has no attribute 'capitalize'

,Products Listing,Manufaktur,Expiry Date,Product Code,no_serifikat,Country,Expire,Institusi
0,ALMOND COOKIES,DMG FOOD INDUSTRIES SDN BHD,NaN,NaN,NaN,NaN,\r\r\n\t\t15/05/2019,JAKIM
1,ALMOND COOKIES,ANN-LEE INDUSTRIES (M) SDN BHD,NaN,NaN,NaN,NaN,\r\r\n\t\t30/09/2019,JAKIM
2,ALMOND COOKIES,360HORIZONZ SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t31/10/2019,JAKIM
3,ALMOND CROISSANT,YEAST ATELIER SDN BHD,NaN,NaN,NaN,NaN,\r\r\n\t\t31/07/2019,JAKIM
4,Apple Juice,Shangrila (Shangrila(Pvt) Limited),NaN,NaN,NaN,NaN,NaN,NaN
5,Apple Juice,Essential Everyday,NaN,NaN,NaN,NaN,NaN,NaN
6,Apple Juice,Shoprite,NaN,NaN,NaN,NaN,NaN,NaN
7,Apple Juice,Ruby Kist,NaN,NaN,NaN,NaN,NaN,NaN
8,Apple Juice,Farm Flavor,NaN,NaN,NaN,NaN,NaN,NaN
9,Apple Juice,Key Food,NaN,NaN,NaN,NaN,NaN,NaN
10,Apple Juice,Schnucks,NaN,NaN,NaN,NaN,NaN,NaN
11,Apple Juice,365,NaN,NaN,NaN,NaN,NaN,NaN
12,ASPARTAME,KIENTAT TRADING SDN. BHD.,NaN,NaN,NaN,NaN,\t\t15/07/2019,JAKIM
13,AURORA SAUCE,LONGSON FOOD PRODUCTS SDN BHD,NaN,NaN,NaN,Malaysia,3/31/2020,JAKIM
14,AYAM BAKAR,RESEPI ARENA SDN BHD,NaN,NaN,NaN,NaN,\r\r\n\t\tSijil Telah Ditarik Balik,JAKIM
15,AYAM BAKAR MADU,RESEPI ARENA SDN BHD,NaN,NaN,NaN,NaN,\r\r\n\t\tSijil Telah Ditarik Balik,JAKIM
16,BAKING POWDER,KIENTAT TRADING SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t15/07/2019,JAKIM
17,BAKING POWDER,360HORIZONZ SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t15/03/2020,JAKIM
18,BAKSO DAGING,CAREY FOOD SERVICES SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t31/12/2020,JAKIM
19,Barbeque,Freshmate Co.,NaN,NaN,NaN,NaN,NaN,NaN
20,BBQ SAUCE,SAUCE EMPIRE MANUFACTURING SDN BHD,NaN,NaN,NaN,NaN,\r\r\n\t\t31/12/2020,JAKIM
21,BBQ Sauce,Shangrila(Pvt) Limited,NaN,NaN,NaN,NaN,NaN,NaN
22,BBQ SAUCE,LONGSON FOOD PRODUCTS SDN BHD,NaN,NaN,NaN,Malaysia,4/30/2020,JAKIM
23,BBQ SEASONING,WORLD PROMINENCE SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t,JAKIM
24,Beef Patties,Patty King,24967 60005,24967 60005,NaN,Canada,NaN,NaN
25,Beef Patties,Al-Safa Halal,24967 45700,24967 45700,NaN,USA,NaN,NaN
26,BEEF PATTY,CAREY FOOD SERVICES SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t31/12/2020,NaN
27,BEEF RENDANG,DELI ARTISAN SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t28/02/2020,NaN
28,Blueberry,Kirkland,NaN,NaN,NaN,NaN,NaN,NaN
29,BLUEBERRY CAKE,HAZEL CAKE HOUSE,NaN,NaN,NaN,NaN,\r\r\n\t\t31/05/2019,NaN
...,...,...,...,...,...,...,...,...
453,Vegetable Oil,Hubberts,66008 00320,66008 00320,NaN,Canada,NaN,NaN
454,Vegetable Oil,Giant,NaN,NaN,NaN,NaN,NaN,NaN
455,Vegetable Oil,Fred Meyer,NaN,NaN,NaN,NaN,NaN,NaN
456,Vegetable Oil,Safeway Kitchens,NaN,NaN,NaN,NaN,NaN,NaN
457,Vegetable Oil,Pantry Essential,NaN,NaN,NaN,NaN,NaN,NaN
458,Vegetable Oil,Stop & Shop,NaN,NaN,NaN,NaN,NaN,NaN
459,Vegetable Oil,Schnucks,NaN,NaN,NaN,NaN,NaN,NaN
460,Vegetable Oil,Market Pantry,NaN,NaN,NaN,NaN,NaN,NaN
461,Vegetable Oil,Kirkland,NaN,NaN,NaN,NaN,NaN,NaN
462,Vegetable Oil,Raley's,NaN,NaN,NaN,NaN,NaN,NaN
463,VEGETARIAN OYSTER FLAVOURED SAUCE,SRI NONA FOOD INDUSTRIES SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t,NaN
464,Vermicelli,Shan,Shan Foods (Pvt) Ltd,NaN,NaN,NaN,NaN,NaN
465,Vermicelli,Safeway Kitchens,NaN,NaN,NaN,NaN,NaN,NaN
466,VIRGIN COCONUT OIL,360HORIZONZ SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t31/05/2019,NaN
467,VIRGIN COCONUT OIL,NUTRAKEM SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t30/06/2019,NaN
468,WAFU DRESSING,SAUCE EMPIRE MANUFACTURING SDN BHD,NaN,NaN,NaN,NaN,\r\r\n\t\t15/02/2020,NaN
469,WAJIK,LULU NYONYA GOODIES SDN BHD,NaN,NaN,NaN,NaN,\r\r\n\t\t15/12/2019,NaN
470,WASABI MAYO,LONGSON FOOD PRODUCTS SDN BHD,NaN,NaN,NaN,Malaysia,4/30/2020,JAKIM
471,WHITE CHOCOLATE,BORDEAUX BAKERY & SWEET (M) SDN BHD,NaN,NaN,NaN,NaN,\r\r\n\t\t15/10/2020,NaN
472,WHITE PEPPER GROUND,360HORIZONZ SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t31/05/2019,NaN
473,WHITE PEPPER POWDER,360HORIZONZ SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t31/05/2019,NaN
474,WHITE PEPPER POWDER,WORLD PROMINENCE SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t30/06/2020,NaN
475,Whole Wheat Bread,Fred Meyer,NaN,NaN,NaN,NaN,NaN,NaN
476,Whole Wheat Bread,Kroger,NaN,NaN,NaN,NaN,NaN,NaN
477,Whole Wheat Bread,Nature's Promise,NaN,NaN,NaN,NaN,NaN,NaN
478,Whole Wheat Bread,Shoprite,NaN,NaN,NaN,NaN,NaN,NaN
479,Whole Wheat Bread,Martin's,NaN,NaN,NaN,NaN,NaN,NaN
480,XANTHAN GUM,360HORIZONZ SDN. BHD.,NaN,NaN,NaN,NaN,\r\r\n\t\t15/03/2020,NaN
481,YAM PASTE,NEW WING CHEONG FOODS INDUSTRIES SDN BHD,NaN,NaN,NaN,NaN,\r\r\n\t\t30/09/2019,NaN
482,Ziti,Market Pantry,NaN,NaN,NaN,NaN,NaN,NaN